config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.routes.draw do
  require "sidekiq_unique_jobs/web"
  mount Sidekiq::Web => "/sidekiq"

  namespace :admin do
    resources :audios
    resources :users

    root to: "users#index"
  end
  get "up" => "rails/health#show", as: :rails_health_check

  draw(:users)

  root "audios/audios#feed"
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def flash_color_classes(type)
    case type
    when "success"
      "bg-green-100 border-green-400 text-green-700"
    when "alert"
      "bg-red-100 border-red-400 text-red-700"
    when "warning"
      "bg-yellow-100 border-yellow-400 text-yellow-700"
    when "notice"
      "bg-blue-100 border-blue-400 text-blue-700"
    else
      "bg-gray-100 border-gray-400 text-gray-700"
    end
  end

  def flash_color_cross(type)
    case type
    when "success"
      "text-green-500"
    when "alert"
      "text-red-500"
    when "warning"
      "text-yellow-500"
    when "notice"
      "text-blue-500"
    else
      "text-gray-500"
    end
  end
end

app/views/application/_alerts.html.erb
<% if flash.any? %>
  <% flash.each do |type, message| %>
    <div class="border px-4 py-3 mb-2 rounded relative <%= flash_color_classes(type) %>" role="alert" data-controller="alert">
      <span class="block sm:inline"><%= message %></span>
      <span class="absolute top-0 bottom-0 right-0 px-4 py-3">
        <svg class="fill-current h-6 w-6 <%= flash_color_cross(type) %>" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" data-action="click->alert#close">
          <title>Close</title>
          <path d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"/>
        </svg>
      </span>
    </div>
  <% end %>
<% end %>

app/views/application/_footer.html.erb
<footer class="bg-white shadow-lg p-4">
  <div class="flex items-center justify-between">
    <span class="text-gray-600">Now Playing: Song Title</span>
    <div class="flex items-center space-x-4">
      <button class="bg-blue-500 text-white p-2 rounded hover:bg-blue-400">
        <i class="iconoir-play"></i>
      </button>
      <button class="bg-blue-500 text-white p-2 rounded hover:bg-blue-400">
        <i class="iconoir-pause"></i>
      </button>
      <button class="bg-blue-500 text-white p-2 rounded hover:bg-blue-400">
        <i class="iconoir-stop"></i>
      </button>
    </div>
  </div>
</footer>

app/views/application/_form_error.html.erb
<% if record.errors.any? %>
  <div class="flex">
    <%= record.errors.full_messages.to_sentence %>
  </div>
<% end %>

app/views/application/_header.html.erb
<header class="bg-white shadow-lg p-4 flex justify-between items-center" data-controller="header">
  <div class="flex items-center space-x-4">
    <h1 class="text-2xl font-bold">
      <%= link_to "Talawa", root_path %>
    </h1>
    <div class="relative">
      <input type="text" placeholder="Search..." class="p-2 border rounded">
    </div>
  </div>
  <div class="flex items-center space-x-4">
    <% if user_signed_in? %>
      <%= link_to "+ Upload", new_user_audio_path(current_user), class: "px-4 py-2 text-gray-700 hover:bg-gray-200" %>
      <%= render "notifications" %>
      <div class="relative">
        <button class="flex items-center" data-action="click->header#toggleDropdown">
          <%= render "users/shared/avatar", user: current_user if user_signed_in? %>
        </button>
        <div id="dropdown" class="absolute right-0 mt-2 w-48 bg-white shadow-lg rounded hidden z-10">
          <%= link_to "My Account", edit_user_registration_path, class: "block px-4 py-2 text-gray-700 hover:bg-gray-200" %>
          <%= link_to "My Playlists", user_playlists_path(current_user), class: "block px-4 py-2 text-gray-700 hover:bg-gray-200" %>
          <%= link_to "Log Out", destroy_user_session_path, class: "block px-4 py-2 text-red-600 hover:bg-red-200", data: { turbo: false } %>
        </div>
      </div>
    <% else %>
      <%= link_to "+ Upload", user_session_path, class: "px-4 py-2 text-gray-700 hover:bg-gray-200" %>
    <% end %>
  </div>
</header>

app/views/application/_notifications.html.erb
<div class="relative">
  <button class="text-gray-700 hover:text-gray-900" data-action="click->header#toggleNotifications">
    <i class="iconoir-bell text-2xl"></i>
    <span class="absolute top-0 right-0 bg-red-500 text-white text-xs rounded-full px-1">3</span>
  </button>
  <div class="absolute right-0 mt-2 w-64 bg-white shadow-lg rounded hidden" id="notifications">
    <ul>
      <li class="flex items-center p-2 hover:bg-gray-200">
        <a href="#" class="flex items-center w-full">
          <i class="iconoir-message text-xl mr-2"></i>
          <span>New message received</span>
        </a>
      </li>
      <li class="flex items-center p-2 hover:bg-gray-200">
        <a href="#" class="flex items-center w-full">
          <i class="iconoir-user text-xl mr-2"></i>
          <span>New follower</span>
        </a>
      </li>
      <li class="flex items-center p-2 hover:bg-gray-200">
        <a href="#" class="flex items-center w-full">
          <i class="iconoir-heart text-xl mr-2"></i>
          <span>Your post was liked</span>
        </a>
      </li>
    </ul>
    <a href="#" class="block text-center text-blue-500 hover:underline py-2">See more notifications</a>
  </div>
</div>

app/views/application/_sidebar.html.erb
<aside class="bg-white w-64 p-4 border-r overflow-y-auto">
  <h2 class="font-bold mb-4">Navigation</h2>
  <ul>
    <li class="mb-2">
      <%= link_to root_path, class: "flex items-center p-2 hover:bg-gray-200 rounded" do %>
        <i class="iconoir-home text-xl"></i>
        <span class="ml-2">Home</span>
      <% end %>
    </li>
    <li class="mb-2">
      <% if user_signed_in? %>
        <%= link_to edit_user_registration_path, class: "flex items-center p-2 hover:bg-gray-200 rounded" do %>
          <i class="iconoir-user text-xl"></i>
          <span class="ml-2">Edit profile</span>
        <% end %>
      <% else %>
        <%= link_to new_user_registration_path, class: "flex items-center p-2 hover:bg-gray-200 rounded" do %>
          <i class="iconoir-user-plus text-xl"></i>
          <span class="ml-2">Sign Up</span>
        <% end %>
      <% end %>
    </li>
    <li class="mb-2">
      <% if user_signed_in? %>
        <%= link_to destroy_user_session_path, class: "flex items-center p-2 hover:bg-gray-200 rounded", data: { turbo: false } do %>
          <i class="iconoir-log-out text-xl"></i>
          <span class="ml-2">Log Out</span>
        <% end %>
      <% else %>
        <%= link_to new_user_session_path, class: "flex items-center p-2 hover:bg-gray-200 rounded" do %>
          <i class="iconoir-log-in text-xl"></i>
          <span class="ml-2">Sign In</span>
        <% end %>
      <% end %>
    </li>
  </ul>
</aside>